name: squint
version: 0.1.0
description: Issue labels for hackers.
author: mockturtl <mockturtl@gmail.com>
homepage: https://github.com/mockturtl/squint
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  args: any
  dotenv: any
  logging: any
  path: any
  pico_log: any
  yaml: any
dev_dependencies:
  test: any
  mockito: any
executables:
  squint: squint
